using System.Text.RegularExpressions;

namespace FundingSouq.Assessment.Api.Infrastructure;

/// <summary>
/// Used to convert api urls generated by asp.net core from PascalCase to kebab-case which is the standard url format. 
/// </summary>
public class KebabParameterTransformer: IOutboundParameterTransformer
{
    public string TransformOutbound(object value) => value is not null 
        ? Regex.Replace(value.ToString()!, "([a-z])([A-Z])", "$1-$2").ToLower() // to kebab 
        : null; 
}